# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows
# https://ci.appveyor.com/project/networkx/networkx

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script interpreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\tools\\appveyor\\run_with_env.cmd"
    CACHE_DIR: "%LOCALAPPDATA%\\pip\\Cache"

  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.8"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.5"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.0"
      PYTHON_ARCH: "64"

install:
  # Install Python (from the official .msi of http://python.org) and pip when
  # not already installed.
  - "powershell .\\tools\\appveyor\\install.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # install required packages
  - "pip install --cache-dir=%CACHE_DIR% -r requirements.txt"

  # Install the build and runtime dependencies of the project.
  # - "%CMD_IN_ENV% pip install --timeout=60 -r requirements.txt"
  - "pip install ."

# Not a .NET project, we build networkx in the install step instead
build: false

test_script:
  # Change to a non-source folder to make sure we run the tests on the
  # installed library.
  - "pushd %TEMP%"
  - "pytest --doctest-modules --pyargs networkx"

cache:
  # Avoid re-downloading large packages
  - '%CACHE_DIR%'
