select = [
    "I",       # isort
    "UP",      # pyupgrade
    "C4",      # flake8-comprehensions
    "E713",    # use 'key not in list'
    "PIE",     # flake8-pie
    "PGH003",  # forbid blanket 'type: ignore' comments
    "PLR0402", # useless import alias
    "SIM101",  # merge 'isinstance' calls
    "SIM109",  # use a tuple for multiple comparisons
    "SIM110",  # convert loop to 'any'
    "SIM111",  # convert loop to 'all'
    "SIM118",  # use 'key in dict'
    "SIM2",    # simplify boolean comparisons
]

target-version = "py39"

[per-file-ignores]
"__init__.py" = ["I"]
"setup.py" = ["I"]
"examples/*.py" = ["I"]
"doc/*.py" = ["I"]
"tools/*.py" = ["I"]
