name: deploy

on:
  push:
    branches: [ master ]

jobs:
  documentation:
    runs-on: Ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Before install
      run: |
        sudo apt-get update
        sudo apt-get install libgdal-dev graphviz graphviz-dev
        sudo apt-get install texlive texlive-latex-extra latexmk
        sudo apt-get install libgeos-dev libproj-dev
        sudo apt-get install libspatialindex-dev
        python3 -m venv ~/venv
        source ~/venv/bin/activate

    - name: Mayavi setup
      run: |
        sudo apt-get --no-install-recommends install -y libxkbcommon-x11-0 optipng libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 xcb libxcb-xfixes0 libxcb-xinerama0 libxcb-shape0
        export DISPLAY=:99
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x200x24 -ac +extension GLX +render -noreset;

    - name: Install packages
      run: |
        pip install --upgrade pip wheel setuptools
        pip install -r requirements.txt
        pip install -r requirements/extra.txt
        pip install -r requirements/example.txt
        pip install -U -r requirements/doc.txt
        export CPLUS_INCLUDE_PATH=/usr/include/gdal
        export C_INCLUDE_PATH=/usr/include/gdal
        pip install gdal==3.0.4
        pip install .
        pip list

    - name: Build docs
      run: |
        make -C doc/ html
        make -C doc/ latexpdf LATEXOPTS="-file-line-error -halt-on-error"
        cp -a doc/build/latex/networkx_reference.pdf doc/build/html/_downloads/.

    - name: Deploy docs
      run: |
        echo "To do"

