name: Labels

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
  push:

env:
  LABELS: ${{ join( github.event.pull_request.labels.*.name, ' ' ) }}

jobs:
  check-type-label:
    name: revr gave label?
    runs-on: ubuntu-latest
    steps:
      - if: "contains( env.LABELS, 'type: ' ) == false"
        run: exit 1
